services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./:/var/www
        environment:
            DB_HOST: postgres
            DB_PORT: 5432
            REDIS_HOST: redis
            REDIS_CLIENT: phpredis
        user: root
        networks:
            - laravel-network
        depends_on:
            - postgres
            - redis

    nginx:
        image: nginx:alpine
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel-network
        depends_on:
            - php

    postgres:
        image: postgres:16
        environment:
            POSTGRES_DB: laravel-docker
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U laravel -d laravel-docker"]
            interval: 5s
            timeout: 5s
            retries: 10
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - laravel-network

    redis:
        image: redis:7-alpine
        command: redis-server --appendonly yes
        volumes:
            - redis_data:/data
        networks:
            - laravel-network

# Volumes
volumes:
    postgres_data:
    redis_data:

# Networks
networks:
    laravel-network:
        driver: bridge
