name: Laravel Docker CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  COMPOSE_PROJECT_NAME: laravel-app
  DB_HOST: postgres
  DB_PORT: 5432
  REDIS_HOST: redis

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 📄 Generate .env
        run: |
          cp .env.example .env
          echo "DB_HOST=postgres" >> .env
          echo "DB_DATABASE=laravel-docker" >> .env
          echo "DB_USERNAME=laravel" >> .env
          echo "DB_PASSWORD=secret" >> .env
          echo "REDIS_HOST=redis" >> .env

      - name: Build and start containers
        run: |
          docker compose up -d --build
          docker compose ps

      - name: Wait for Laravel setup completion
        run: |
          start_time=$(date +%s)
          timeout=600
          while true; do
            if docker compose logs php 2>&1 | grep -q "Start PHP-FPM"; then
              echo "Laravel setup completed successfully!"
              break
            fi

            current_time=$(date +%s)
            elapsed=$((current_time - start_time))

            if [ "$elapsed" -gt "$timeout" ]; then
              echo "❌ Timeout waiting for Laravel setup after ${elapsed}s"
              docker compose logs php
              exit 1
            fi
            
            echo "🔍 Latest PHP logs:"
            docker compose logs php | tail -n 20

            echo "Still waiting... (${elapsed}s elapsed)"
            sleep 30
          done

      # - name: Run tests
      #   run: docker compose exec -T php php artisan test

      - name: Stop containers
        if: always()
        run: docker compose down
